// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: round_trip.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoundTrip struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Token        string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	FlightNumber string                 `protobuf:"bytes,2,opt,name=flight_number,json=flightNumber,proto3" json:"flight_number,omitempty"`
	Price        *RoundTrip_Price       `protobuf:"bytes,3,opt,name=price,proto3" json:"price,omitempty"`
	// unsure on what this value represents, should be set to 28.
	Unknown       int32 `protobuf:"varint,7,opt,name=unknown,proto3" json:"unknown,omitempty"`
	UsdPrice      int32 `protobuf:"varint,14,opt,name=usd_price,json=usdPrice,proto3" json:"usd_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoundTrip) Reset() {
	*x = RoundTrip{}
	mi := &file_round_trip_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoundTrip) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoundTrip) ProtoMessage() {}

func (x *RoundTrip) ProtoReflect() protoreflect.Message {
	mi := &file_round_trip_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoundTrip.ProtoReflect.Descriptor instead.
func (*RoundTrip) Descriptor() ([]byte, []int) {
	return file_round_trip_proto_rawDescGZIP(), []int{0}
}

func (x *RoundTrip) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RoundTrip) GetFlightNumber() string {
	if x != nil {
		return x.FlightNumber
	}
	return ""
}

func (x *RoundTrip) GetPrice() *RoundTrip_Price {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *RoundTrip) GetUnknown() int32 {
	if x != nil {
		return x.Unknown
	}
	return 0
}

func (x *RoundTrip) GetUsdPrice() int32 {
	if x != nil {
		return x.UsdPrice
	}
	return 0
}

type RoundTrip_Price struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        int32                  `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Precision     int32                  `protobuf:"varint,2,opt,name=precision,proto3" json:"precision,omitempty"`
	Currency      string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoundTrip_Price) Reset() {
	*x = RoundTrip_Price{}
	mi := &file_round_trip_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoundTrip_Price) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoundTrip_Price) ProtoMessage() {}

func (x *RoundTrip_Price) ProtoReflect() protoreflect.Message {
	mi := &file_round_trip_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoundTrip_Price.ProtoReflect.Descriptor instead.
func (*RoundTrip_Price) Descriptor() ([]byte, []int) {
	return file_round_trip_proto_rawDescGZIP(), []int{0, 0}
}

func (x *RoundTrip_Price) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *RoundTrip_Price) GetPrecision() int32 {
	if x != nil {
		return x.Precision
	}
	return 0
}

func (x *RoundTrip_Price) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

var File_round_trip_proto protoreflect.FileDescriptor

const file_round_trip_proto_rawDesc = "" +
	"\n" +
	"\x10round_trip.proto\x12\x03url\"\x84\x02\n" +
	"\tRoundTrip\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12#\n" +
	"\rflight_number\x18\x02 \x01(\tR\fflightNumber\x12*\n" +
	"\x05price\x18\x03 \x01(\v2\x14.url.RoundTrip.PriceR\x05price\x12\x18\n" +
	"\aunknown\x18\a \x01(\x05R\aunknown\x12\x1b\n" +
	"\tusd_price\x18\x0e \x01(\x05R\busdPrice\x1aY\n" +
	"\x05Price\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x05R\x06amount\x12\x1c\n" +
	"\tprecision\x18\x02 \x01(\x05R\tprecision\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrencyB.Z,github.com/tobyrushton/gflights//internal/pbb\x06proto3"

var (
	file_round_trip_proto_rawDescOnce sync.Once
	file_round_trip_proto_rawDescData []byte
)

func file_round_trip_proto_rawDescGZIP() []byte {
	file_round_trip_proto_rawDescOnce.Do(func() {
		file_round_trip_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_round_trip_proto_rawDesc), len(file_round_trip_proto_rawDesc)))
	})
	return file_round_trip_proto_rawDescData
}

var file_round_trip_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_round_trip_proto_goTypes = []any{
	(*RoundTrip)(nil),       // 0: url.RoundTrip
	(*RoundTrip_Price)(nil), // 1: url.RoundTrip.Price
}
var file_round_trip_proto_depIdxs = []int32{
	1, // 0: url.RoundTrip.price:type_name -> url.RoundTrip.Price
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_round_trip_proto_init() }
func file_round_trip_proto_init() {
	if File_round_trip_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_round_trip_proto_rawDesc), len(file_round_trip_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_round_trip_proto_goTypes,
		DependencyIndexes: file_round_trip_proto_depIdxs,
		MessageInfos:      file_round_trip_proto_msgTypes,
	}.Build()
	File_round_trip_proto = out.File
	file_round_trip_proto_goTypes = nil
	file_round_trip_proto_depIdxs = nil
}
