// https://github.com/krisukox/google-flights-api/blob/main/flights/internal/urlpb/url.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: url.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Stops int32

const (
	Stops_NONSTOP Stops = 0
	Stops_STOP1   Stops = 1
	Stops_STOP2   Stops = 2
)

// Enum value maps for Stops.
var (
	Stops_name = map[int32]string{
		0: "NONSTOP",
		1: "STOP1",
		2: "STOP2",
	}
	Stops_value = map[string]int32{
		"NONSTOP": 0,
		"STOP1":   1,
		"STOP2":   2,
	}
)

func (x Stops) Enum() *Stops {
	p := new(Stops)
	*p = x
	return p
}

func (x Stops) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Stops) Descriptor() protoreflect.EnumDescriptor {
	return file_url_proto_enumTypes[0].Descriptor()
}

func (Stops) Type() protoreflect.EnumType {
	return &file_url_proto_enumTypes[0]
}

func (x Stops) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Stops.Descriptor instead.
func (Stops) EnumDescriptor() ([]byte, []int) {
	return file_url_proto_rawDescGZIP(), []int{0}
}

type LocationType int32

const (
	LocationType_UNSPECIFIED_L LocationType = 0
	LocationType_AIRPORT       LocationType = 1
	LocationType_CITY          LocationType = 2
)

// Enum value maps for LocationType.
var (
	LocationType_name = map[int32]string{
		0: "UNSPECIFIED_L",
		1: "AIRPORT",
		2: "CITY",
	}
	LocationType_value = map[string]int32{
		"UNSPECIFIED_L": 0,
		"AIRPORT":       1,
		"CITY":          2,
	}
)

func (x LocationType) Enum() *LocationType {
	p := new(LocationType)
	*p = x
	return p
}

func (x LocationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LocationType) Descriptor() protoreflect.EnumDescriptor {
	return file_url_proto_enumTypes[1].Descriptor()
}

func (LocationType) Type() protoreflect.EnumType {
	return &file_url_proto_enumTypes[1]
}

func (x LocationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LocationType.Descriptor instead.
func (LocationType) EnumDescriptor() ([]byte, []int) {
	return file_url_proto_rawDescGZIP(), []int{1}
}

type Traveler int32

const (
	Traveler_UNSPECIFIED_T  Traveler = 0
	Traveler_ADULT          Traveler = 1
	Traveler_CHILD          Traveler = 2
	Traveler_INFANT_ON_LAP  Traveler = 3
	Traveler_INFANT_IN_SEAT Traveler = 4
)

// Enum value maps for Traveler.
var (
	Traveler_name = map[int32]string{
		0: "UNSPECIFIED_T",
		1: "ADULT",
		2: "CHILD",
		3: "INFANT_ON_LAP",
		4: "INFANT_IN_SEAT",
	}
	Traveler_value = map[string]int32{
		"UNSPECIFIED_T":  0,
		"ADULT":          1,
		"CHILD":          2,
		"INFANT_ON_LAP":  3,
		"INFANT_IN_SEAT": 4,
	}
)

func (x Traveler) Enum() *Traveler {
	p := new(Traveler)
	*p = x
	return p
}

func (x Traveler) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Traveler) Descriptor() protoreflect.EnumDescriptor {
	return file_url_proto_enumTypes[2].Descriptor()
}

func (Traveler) Type() protoreflect.EnumType {
	return &file_url_proto_enumTypes[2]
}

func (x Traveler) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Traveler.Descriptor instead.
func (Traveler) EnumDescriptor() ([]byte, []int) {
	return file_url_proto_rawDescGZIP(), []int{2}
}

type Class int32

const (
	Class_UNSPECIFIED_CLASS Class = 0
	Class_ECONOMY           Class = 1
	Class_PREMIUM_ECONOMY   Class = 2
	Class_BUSINESS          Class = 3
	Class_FIRST             Class = 4
)

// Enum value maps for Class.
var (
	Class_name = map[int32]string{
		0: "UNSPECIFIED_CLASS",
		1: "ECONOMY",
		2: "PREMIUM_ECONOMY",
		3: "BUSINESS",
		4: "FIRST",
	}
	Class_value = map[string]int32{
		"UNSPECIFIED_CLASS": 0,
		"ECONOMY":           1,
		"PREMIUM_ECONOMY":   2,
		"BUSINESS":          3,
		"FIRST":             4,
	}
)

func (x Class) Enum() *Class {
	p := new(Class)
	*p = x
	return p
}

func (x Class) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Class) Descriptor() protoreflect.EnumDescriptor {
	return file_url_proto_enumTypes[3].Descriptor()
}

func (Class) Type() protoreflect.EnumType {
	return &file_url_proto_enumTypes[3]
}

func (x Class) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Class.Descriptor instead.
func (Class) EnumDescriptor() ([]byte, []int) {
	return file_url_proto_rawDescGZIP(), []int{3}
}

type TripType int32

const (
	TripType_UNSPECIFIED_TRIP TripType = 0
	TripType_ROUND_TRIP       TripType = 1
	TripType_ONE_WAY          TripType = 2
)

// Enum value maps for TripType.
var (
	TripType_name = map[int32]string{
		0: "UNSPECIFIED_TRIP",
		1: "ROUND_TRIP",
		2: "ONE_WAY",
	}
	TripType_value = map[string]int32{
		"UNSPECIFIED_TRIP": 0,
		"ROUND_TRIP":       1,
		"ONE_WAY":          2,
	}
)

func (x TripType) Enum() *TripType {
	p := new(TripType)
	*p = x
	return p
}

func (x TripType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TripType) Descriptor() protoreflect.EnumDescriptor {
	return file_url_proto_enumTypes[4].Descriptor()
}

func (TripType) Type() protoreflect.EnumType {
	return &file_url_proto_enumTypes[4]
}

func (x TripType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TripType.Descriptor instead.
func (TripType) EnumDescriptor() ([]byte, []int) {
	return file_url_proto_rawDescGZIP(), []int{4}
}

type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          LocationType           `protobuf:"varint,1,opt,name=type,proto3,enum=url.LocationType" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_url_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_url_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_url_proto_rawDescGZIP(), []int{0}
}

func (x *Location) GetType() LocationType {
	if x != nil {
		return x.Type
	}
	return LocationType_UNSPECIFIED_L
}

func (x *Location) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SearchFlight struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Stops         *Stops                 `protobuf:"varint,5,opt,name=stops,proto3,enum=url.Stops,oneof" json:"stops,omitempty"`
	SrcLocations  []*Location            `protobuf:"bytes,13,rep,name=srcLocations,proto3" json:"srcLocations,omitempty"`
	DstLocations  []*Location            `protobuf:"bytes,14,rep,name=dstLocations,proto3" json:"dstLocations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchFlight) Reset() {
	*x = SearchFlight{}
	mi := &file_url_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchFlight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchFlight) ProtoMessage() {}

func (x *SearchFlight) ProtoReflect() protoreflect.Message {
	mi := &file_url_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchFlight.ProtoReflect.Descriptor instead.
func (*SearchFlight) Descriptor() ([]byte, []int) {
	return file_url_proto_rawDescGZIP(), []int{1}
}

func (x *SearchFlight) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *SearchFlight) GetStops() Stops {
	if x != nil && x.Stops != nil {
		return *x.Stops
	}
	return Stops_NONSTOP
}

func (x *SearchFlight) GetSrcLocations() []*Location {
	if x != nil {
		return x.SrcLocations
	}
	return nil
}

func (x *SearchFlight) GetDstLocations() []*Location {
	if x != nil {
		return x.DstLocations
	}
	return nil
}

type Flight struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DepCode       string                 `protobuf:"bytes,1,opt,name=dep_code,json=depCode,proto3" json:"dep_code,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	DestCode      string                 `protobuf:"bytes,3,opt,name=dest_code,json=destCode,proto3" json:"dest_code,omitempty"`
	AirlineCode   string                 `protobuf:"bytes,5,opt,name=airline_code,json=airlineCode,proto3" json:"airline_code,omitempty"`
	FlightNumber  string                 `protobuf:"bytes,6,opt,name=flight_number,json=flightNumber,proto3" json:"flight_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Flight) Reset() {
	*x = Flight{}
	mi := &file_url_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Flight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Flight) ProtoMessage() {}

func (x *Flight) ProtoReflect() protoreflect.Message {
	mi := &file_url_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Flight.ProtoReflect.Descriptor instead.
func (*Flight) Descriptor() ([]byte, []int) {
	return file_url_proto_rawDescGZIP(), []int{2}
}

func (x *Flight) GetDepCode() string {
	if x != nil {
		return x.DepCode
	}
	return ""
}

func (x *Flight) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *Flight) GetDestCode() string {
	if x != nil {
		return x.DestCode
	}
	return ""
}

func (x *Flight) GetAirlineCode() string {
	if x != nil {
		return x.AirlineCode
	}
	return ""
}

func (x *Flight) GetFlightNumber() string {
	if x != nil {
		return x.FlightNumber
	}
	return ""
}

type BookingFlight struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Flights       []*Flight              `protobuf:"bytes,4,rep,name=flights,proto3" json:"flights,omitempty"`
	SrcLocations  []*Location            `protobuf:"bytes,13,rep,name=srcLocations,proto3" json:"srcLocations,omitempty"`
	DstLocations  []*Location            `protobuf:"bytes,14,rep,name=dstLocations,proto3" json:"dstLocations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookingFlight) Reset() {
	*x = BookingFlight{}
	mi := &file_url_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingFlight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingFlight) ProtoMessage() {}

func (x *BookingFlight) ProtoReflect() protoreflect.Message {
	mi := &file_url_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingFlight.ProtoReflect.Descriptor instead.
func (*BookingFlight) Descriptor() ([]byte, []int) {
	return file_url_proto_rawDescGZIP(), []int{3}
}

func (x *BookingFlight) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *BookingFlight) GetFlights() []*Flight {
	if x != nil {
		return x.Flights
	}
	return nil
}

func (x *BookingFlight) GetSrcLocations() []*Location {
	if x != nil {
		return x.SrcLocations
	}
	return nil
}

func (x *BookingFlight) GetDstLocations() []*Location {
	if x != nil {
		return x.DstLocations
	}
	return nil
}

type SearchUrl struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Flight        []*SearchFlight        `protobuf:"bytes,3,rep,name=flight,proto3" json:"flight,omitempty"`
	Travelers     []Traveler             `protobuf:"varint,8,rep,packed,name=travelers,proto3,enum=url.Traveler" json:"travelers,omitempty"`
	Class         Class                  `protobuf:"varint,9,opt,name=class,proto3,enum=url.Class" json:"class,omitempty"`
	TripType      TripType               `protobuf:"varint,19,opt,name=tripType,proto3,enum=url.TripType" json:"tripType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUrl) Reset() {
	*x = SearchUrl{}
	mi := &file_url_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUrl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUrl) ProtoMessage() {}

func (x *SearchUrl) ProtoReflect() protoreflect.Message {
	mi := &file_url_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUrl.ProtoReflect.Descriptor instead.
func (*SearchUrl) Descriptor() ([]byte, []int) {
	return file_url_proto_rawDescGZIP(), []int{4}
}

func (x *SearchUrl) GetFlight() []*SearchFlight {
	if x != nil {
		return x.Flight
	}
	return nil
}

func (x *SearchUrl) GetTravelers() []Traveler {
	if x != nil {
		return x.Travelers
	}
	return nil
}

func (x *SearchUrl) GetClass() Class {
	if x != nil {
		return x.Class
	}
	return Class_UNSPECIFIED_CLASS
}

func (x *SearchUrl) GetTripType() TripType {
	if x != nil {
		return x.TripType
	}
	return TripType_UNSPECIFIED_TRIP
}

type BookingUrl struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Flight        []*BookingFlight       `protobuf:"bytes,3,rep,name=flight,proto3" json:"flight,omitempty"`
	Travelers     []Traveler             `protobuf:"varint,8,rep,packed,name=travelers,proto3,enum=url.Traveler" json:"travelers,omitempty"`
	Class         Class                  `protobuf:"varint,9,opt,name=class,proto3,enum=url.Class" json:"class,omitempty"`
	TripType      TripType               `protobuf:"varint,19,opt,name=tripType,proto3,enum=url.TripType" json:"tripType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookingUrl) Reset() {
	*x = BookingUrl{}
	mi := &file_url_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingUrl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingUrl) ProtoMessage() {}

func (x *BookingUrl) ProtoReflect() protoreflect.Message {
	mi := &file_url_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingUrl.ProtoReflect.Descriptor instead.
func (*BookingUrl) Descriptor() ([]byte, []int) {
	return file_url_proto_rawDescGZIP(), []int{5}
}

func (x *BookingUrl) GetFlight() []*BookingFlight {
	if x != nil {
		return x.Flight
	}
	return nil
}

func (x *BookingUrl) GetTravelers() []Traveler {
	if x != nil {
		return x.Travelers
	}
	return nil
}

func (x *BookingUrl) GetClass() Class {
	if x != nil {
		return x.Class
	}
	return Class_UNSPECIFIED_CLASS
}

func (x *BookingUrl) GetTripType() TripType {
	if x != nil {
		return x.TripType
	}
	return TripType_UNSPECIFIED_TRIP
}

var File_url_proto protoreflect.FileDescriptor

const file_url_proto_rawDesc = "" +
	"\n" +
	"\turl.proto\x12\x03url\"E\n" +
	"\bLocation\x12%\n" +
	"\x04type\x18\x01 \x01(\x0e2\x11.url.LocationTypeR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xb9\x01\n" +
	"\fSearchFlight\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12%\n" +
	"\x05stops\x18\x05 \x01(\x0e2\n" +
	".url.StopsH\x00R\x05stops\x88\x01\x01\x121\n" +
	"\fsrcLocations\x18\r \x03(\v2\r.url.LocationR\fsrcLocations\x121\n" +
	"\fdstLocations\x18\x0e \x03(\v2\r.url.LocationR\fdstLocationsB\b\n" +
	"\x06_stops\"\x9c\x01\n" +
	"\x06Flight\x12\x19\n" +
	"\bdep_code\x18\x01 \x01(\tR\adepCode\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12\x1b\n" +
	"\tdest_code\x18\x03 \x01(\tR\bdestCode\x12!\n" +
	"\fairline_code\x18\x05 \x01(\tR\vairlineCode\x12#\n" +
	"\rflight_number\x18\x06 \x01(\tR\fflightNumber\"\xb0\x01\n" +
	"\rBookingFlight\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12%\n" +
	"\aflights\x18\x04 \x03(\v2\v.url.FlightR\aflights\x121\n" +
	"\fsrcLocations\x18\r \x03(\v2\r.url.LocationR\fsrcLocations\x121\n" +
	"\fdstLocations\x18\x0e \x03(\v2\r.url.LocationR\fdstLocations\"\xb0\x01\n" +
	"\tSearchUrl\x12)\n" +
	"\x06flight\x18\x03 \x03(\v2\x11.url.SearchFlightR\x06flight\x12+\n" +
	"\ttravelers\x18\b \x03(\x0e2\r.url.TravelerR\ttravelers\x12 \n" +
	"\x05class\x18\t \x01(\x0e2\n" +
	".url.ClassR\x05class\x12)\n" +
	"\btripType\x18\x13 \x01(\x0e2\r.url.TripTypeR\btripType\"\xb2\x01\n" +
	"\n" +
	"BookingUrl\x12*\n" +
	"\x06flight\x18\x03 \x03(\v2\x12.url.BookingFlightR\x06flight\x12+\n" +
	"\ttravelers\x18\b \x03(\x0e2\r.url.TravelerR\ttravelers\x12 \n" +
	"\x05class\x18\t \x01(\x0e2\n" +
	".url.ClassR\x05class\x12)\n" +
	"\btripType\x18\x13 \x01(\x0e2\r.url.TripTypeR\btripType**\n" +
	"\x05Stops\x12\v\n" +
	"\aNONSTOP\x10\x00\x12\t\n" +
	"\x05STOP1\x10\x01\x12\t\n" +
	"\x05STOP2\x10\x02*8\n" +
	"\fLocationType\x12\x11\n" +
	"\rUNSPECIFIED_L\x10\x00\x12\v\n" +
	"\aAIRPORT\x10\x01\x12\b\n" +
	"\x04CITY\x10\x02*Z\n" +
	"\bTraveler\x12\x11\n" +
	"\rUNSPECIFIED_T\x10\x00\x12\t\n" +
	"\x05ADULT\x10\x01\x12\t\n" +
	"\x05CHILD\x10\x02\x12\x11\n" +
	"\rINFANT_ON_LAP\x10\x03\x12\x12\n" +
	"\x0eINFANT_IN_SEAT\x10\x04*Y\n" +
	"\x05Class\x12\x15\n" +
	"\x11UNSPECIFIED_CLASS\x10\x00\x12\v\n" +
	"\aECONOMY\x10\x01\x12\x13\n" +
	"\x0fPREMIUM_ECONOMY\x10\x02\x12\f\n" +
	"\bBUSINESS\x10\x03\x12\t\n" +
	"\x05FIRST\x10\x04*=\n" +
	"\bTripType\x12\x14\n" +
	"\x10UNSPECIFIED_TRIP\x10\x00\x12\x0e\n" +
	"\n" +
	"ROUND_TRIP\x10\x01\x12\v\n" +
	"\aONE_WAY\x10\x02B-Z+github.com/tobyrushton/gflights/internal/pbb\x06proto3"

var (
	file_url_proto_rawDescOnce sync.Once
	file_url_proto_rawDescData []byte
)

func file_url_proto_rawDescGZIP() []byte {
	file_url_proto_rawDescOnce.Do(func() {
		file_url_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_url_proto_rawDesc), len(file_url_proto_rawDesc)))
	})
	return file_url_proto_rawDescData
}

var file_url_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_url_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_url_proto_goTypes = []any{
	(Stops)(0),            // 0: url.Stops
	(LocationType)(0),     // 1: url.LocationType
	(Traveler)(0),         // 2: url.Traveler
	(Class)(0),            // 3: url.Class
	(TripType)(0),         // 4: url.TripType
	(*Location)(nil),      // 5: url.Location
	(*SearchFlight)(nil),  // 6: url.SearchFlight
	(*Flight)(nil),        // 7: url.Flight
	(*BookingFlight)(nil), // 8: url.BookingFlight
	(*SearchUrl)(nil),     // 9: url.SearchUrl
	(*BookingUrl)(nil),    // 10: url.BookingUrl
}
var file_url_proto_depIdxs = []int32{
	1,  // 0: url.Location.type:type_name -> url.LocationType
	0,  // 1: url.SearchFlight.stops:type_name -> url.Stops
	5,  // 2: url.SearchFlight.srcLocations:type_name -> url.Location
	5,  // 3: url.SearchFlight.dstLocations:type_name -> url.Location
	7,  // 4: url.BookingFlight.flights:type_name -> url.Flight
	5,  // 5: url.BookingFlight.srcLocations:type_name -> url.Location
	5,  // 6: url.BookingFlight.dstLocations:type_name -> url.Location
	6,  // 7: url.SearchUrl.flight:type_name -> url.SearchFlight
	2,  // 8: url.SearchUrl.travelers:type_name -> url.Traveler
	3,  // 9: url.SearchUrl.class:type_name -> url.Class
	4,  // 10: url.SearchUrl.tripType:type_name -> url.TripType
	8,  // 11: url.BookingUrl.flight:type_name -> url.BookingFlight
	2,  // 12: url.BookingUrl.travelers:type_name -> url.Traveler
	3,  // 13: url.BookingUrl.class:type_name -> url.Class
	4,  // 14: url.BookingUrl.tripType:type_name -> url.TripType
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_url_proto_init() }
func file_url_proto_init() {
	if File_url_proto != nil {
		return
	}
	file_url_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_url_proto_rawDesc), len(file_url_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_url_proto_goTypes,
		DependencyIndexes: file_url_proto_depIdxs,
		EnumInfos:         file_url_proto_enumTypes,
		MessageInfos:      file_url_proto_msgTypes,
	}.Build()
	File_url_proto = out.File
	file_url_proto_goTypes = nil
	file_url_proto_depIdxs = nil
}
