// https://github.com/krisukox/google-flights-api/blob/main/flights/internal/urlpb/url.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: url.proto

package url

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Url_Stops int32

const (
	Url_NONSTOP Url_Stops = 0
	Url_STOP1   Url_Stops = 1
	Url_STOP2   Url_Stops = 2
)

// Enum value maps for Url_Stops.
var (
	Url_Stops_name = map[int32]string{
		0: "NONSTOP",
		1: "STOP1",
		2: "STOP2",
	}
	Url_Stops_value = map[string]int32{
		"NONSTOP": 0,
		"STOP1":   1,
		"STOP2":   2,
	}
)

func (x Url_Stops) Enum() *Url_Stops {
	p := new(Url_Stops)
	*p = x
	return p
}

func (x Url_Stops) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Url_Stops) Descriptor() protoreflect.EnumDescriptor {
	return file_url_proto_enumTypes[0].Descriptor()
}

func (Url_Stops) Type() protoreflect.EnumType {
	return &file_url_proto_enumTypes[0]
}

func (x Url_Stops) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Url_Stops.Descriptor instead.
func (Url_Stops) EnumDescriptor() ([]byte, []int) {
	return file_url_proto_rawDescGZIP(), []int{0, 0}
}

type Url_LocationType int32

const (
	Url_UNSPECIFIED_L Url_LocationType = 0
	Url_AIRPORT       Url_LocationType = 1
	Url_CITY          Url_LocationType = 2
)

// Enum value maps for Url_LocationType.
var (
	Url_LocationType_name = map[int32]string{
		0: "UNSPECIFIED_L",
		1: "AIRPORT",
		2: "CITY",
	}
	Url_LocationType_value = map[string]int32{
		"UNSPECIFIED_L": 0,
		"AIRPORT":       1,
		"CITY":          2,
	}
)

func (x Url_LocationType) Enum() *Url_LocationType {
	p := new(Url_LocationType)
	*p = x
	return p
}

func (x Url_LocationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Url_LocationType) Descriptor() protoreflect.EnumDescriptor {
	return file_url_proto_enumTypes[1].Descriptor()
}

func (Url_LocationType) Type() protoreflect.EnumType {
	return &file_url_proto_enumTypes[1]
}

func (x Url_LocationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Url_LocationType.Descriptor instead.
func (Url_LocationType) EnumDescriptor() ([]byte, []int) {
	return file_url_proto_rawDescGZIP(), []int{0, 1}
}

type Url_Traveler int32

const (
	Url_UNSPECIFIED_T  Url_Traveler = 0
	Url_ADULT          Url_Traveler = 1
	Url_CHILD          Url_Traveler = 2
	Url_INFANT_ON_LAP  Url_Traveler = 3
	Url_INFANT_IN_SEAT Url_Traveler = 4
)

// Enum value maps for Url_Traveler.
var (
	Url_Traveler_name = map[int32]string{
		0: "UNSPECIFIED_T",
		1: "ADULT",
		2: "CHILD",
		3: "INFANT_ON_LAP",
		4: "INFANT_IN_SEAT",
	}
	Url_Traveler_value = map[string]int32{
		"UNSPECIFIED_T":  0,
		"ADULT":          1,
		"CHILD":          2,
		"INFANT_ON_LAP":  3,
		"INFANT_IN_SEAT": 4,
	}
)

func (x Url_Traveler) Enum() *Url_Traveler {
	p := new(Url_Traveler)
	*p = x
	return p
}

func (x Url_Traveler) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Url_Traveler) Descriptor() protoreflect.EnumDescriptor {
	return file_url_proto_enumTypes[2].Descriptor()
}

func (Url_Traveler) Type() protoreflect.EnumType {
	return &file_url_proto_enumTypes[2]
}

func (x Url_Traveler) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Url_Traveler.Descriptor instead.
func (Url_Traveler) EnumDescriptor() ([]byte, []int) {
	return file_url_proto_rawDescGZIP(), []int{0, 2}
}

type Url_Class int32

const (
	Url_UNSPECIFIED_CLASS Url_Class = 0
	Url_ECONOMY           Url_Class = 1
	Url_PREMIUM_ECONOMY   Url_Class = 2
	Url_BUSINESS          Url_Class = 3
	Url_FIRST             Url_Class = 4
)

// Enum value maps for Url_Class.
var (
	Url_Class_name = map[int32]string{
		0: "UNSPECIFIED_CLASS",
		1: "ECONOMY",
		2: "PREMIUM_ECONOMY",
		3: "BUSINESS",
		4: "FIRST",
	}
	Url_Class_value = map[string]int32{
		"UNSPECIFIED_CLASS": 0,
		"ECONOMY":           1,
		"PREMIUM_ECONOMY":   2,
		"BUSINESS":          3,
		"FIRST":             4,
	}
)

func (x Url_Class) Enum() *Url_Class {
	p := new(Url_Class)
	*p = x
	return p
}

func (x Url_Class) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Url_Class) Descriptor() protoreflect.EnumDescriptor {
	return file_url_proto_enumTypes[3].Descriptor()
}

func (Url_Class) Type() protoreflect.EnumType {
	return &file_url_proto_enumTypes[3]
}

func (x Url_Class) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Url_Class.Descriptor instead.
func (Url_Class) EnumDescriptor() ([]byte, []int) {
	return file_url_proto_rawDescGZIP(), []int{0, 3}
}

type Url_TripType int32

const (
	Url_UNSPECIFIED_TRIP Url_TripType = 0
	Url_ROUND_TRIP       Url_TripType = 1
	Url_ONE_WAY          Url_TripType = 2
)

// Enum value maps for Url_TripType.
var (
	Url_TripType_name = map[int32]string{
		0: "UNSPECIFIED_TRIP",
		1: "ROUND_TRIP",
		2: "ONE_WAY",
	}
	Url_TripType_value = map[string]int32{
		"UNSPECIFIED_TRIP": 0,
		"ROUND_TRIP":       1,
		"ONE_WAY":          2,
	}
)

func (x Url_TripType) Enum() *Url_TripType {
	p := new(Url_TripType)
	*p = x
	return p
}

func (x Url_TripType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Url_TripType) Descriptor() protoreflect.EnumDescriptor {
	return file_url_proto_enumTypes[4].Descriptor()
}

func (Url_TripType) Type() protoreflect.EnumType {
	return &file_url_proto_enumTypes[4]
}

func (x Url_TripType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Url_TripType.Descriptor instead.
func (Url_TripType) EnumDescriptor() ([]byte, []int) {
	return file_url_proto_rawDescGZIP(), []int{0, 4}
}

type Url struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Flight        []*Url_Flight          `protobuf:"bytes,3,rep,name=flight,proto3" json:"flight,omitempty"`
	Travelers     []Url_Traveler         `protobuf:"varint,8,rep,packed,name=travelers,proto3,enum=url.Url_Traveler" json:"travelers,omitempty"`
	Class         Url_Class              `protobuf:"varint,9,opt,name=class,proto3,enum=url.Url_Class" json:"class,omitempty"`
	TripType      Url_TripType           `protobuf:"varint,19,opt,name=tripType,proto3,enum=url.Url_TripType" json:"tripType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Url) Reset() {
	*x = Url{}
	mi := &file_url_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Url) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Url) ProtoMessage() {}

func (x *Url) ProtoReflect() protoreflect.Message {
	mi := &file_url_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Url.ProtoReflect.Descriptor instead.
func (*Url) Descriptor() ([]byte, []int) {
	return file_url_proto_rawDescGZIP(), []int{0}
}

func (x *Url) GetFlight() []*Url_Flight {
	if x != nil {
		return x.Flight
	}
	return nil
}

func (x *Url) GetTravelers() []Url_Traveler {
	if x != nil {
		return x.Travelers
	}
	return nil
}

func (x *Url) GetClass() Url_Class {
	if x != nil {
		return x.Class
	}
	return Url_UNSPECIFIED_CLASS
}

func (x *Url) GetTripType() Url_TripType {
	if x != nil {
		return x.TripType
	}
	return Url_UNSPECIFIED_TRIP
}

type Url_Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          Url_LocationType       `protobuf:"varint,1,opt,name=type,proto3,enum=url.Url_LocationType" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Url_Location) Reset() {
	*x = Url_Location{}
	mi := &file_url_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Url_Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Url_Location) ProtoMessage() {}

func (x *Url_Location) ProtoReflect() protoreflect.Message {
	mi := &file_url_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Url_Location.ProtoReflect.Descriptor instead.
func (*Url_Location) Descriptor() ([]byte, []int) {
	return file_url_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Url_Location) GetType() Url_LocationType {
	if x != nil {
		return x.Type
	}
	return Url_UNSPECIFIED_L
}

func (x *Url_Location) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Url_Flight struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Stops         *Url_Stops             `protobuf:"varint,5,opt,name=stops,proto3,enum=url.Url_Stops,oneof" json:"stops,omitempty"`
	SrcLocations  []*Url_Location        `protobuf:"bytes,13,rep,name=srcLocations,proto3" json:"srcLocations,omitempty"`
	DstLocations  []*Url_Location        `protobuf:"bytes,14,rep,name=dstLocations,proto3" json:"dstLocations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Url_Flight) Reset() {
	*x = Url_Flight{}
	mi := &file_url_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Url_Flight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Url_Flight) ProtoMessage() {}

func (x *Url_Flight) ProtoReflect() protoreflect.Message {
	mi := &file_url_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Url_Flight.ProtoReflect.Descriptor instead.
func (*Url_Flight) Descriptor() ([]byte, []int) {
	return file_url_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Url_Flight) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *Url_Flight) GetStops() Url_Stops {
	if x != nil && x.Stops != nil {
		return *x.Stops
	}
	return Url_NONSTOP
}

func (x *Url_Flight) GetSrcLocations() []*Url_Location {
	if x != nil {
		return x.SrcLocations
	}
	return nil
}

func (x *Url_Flight) GetDstLocations() []*Url_Location {
	if x != nil {
		return x.DstLocations
	}
	return nil
}

var File_url_proto protoreflect.FileDescriptor

const file_url_proto_rawDesc = "" +
	"\n" +
	"\turl.proto\x12\x03url\"\x9d\x06\n" +
	"\x03Url\x12'\n" +
	"\x06flight\x18\x03 \x03(\v2\x0f.url.Url.FlightR\x06flight\x12/\n" +
	"\ttravelers\x18\b \x03(\x0e2\x11.url.Url.TravelerR\ttravelers\x12$\n" +
	"\x05class\x18\t \x01(\x0e2\x0e.url.Url.ClassR\x05class\x12-\n" +
	"\btripType\x18\x13 \x01(\x0e2\x11.url.Url.TripTypeR\btripType\x1aI\n" +
	"\bLocation\x12)\n" +
	"\x04type\x18\x01 \x01(\x0e2\x15.url.Url.LocationTypeR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x1a\xbf\x01\n" +
	"\x06Flight\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12)\n" +
	"\x05stops\x18\x05 \x01(\x0e2\x0e.url.Url.StopsH\x00R\x05stops\x88\x01\x01\x125\n" +
	"\fsrcLocations\x18\r \x03(\v2\x11.url.Url.LocationR\fsrcLocations\x125\n" +
	"\fdstLocations\x18\x0e \x03(\v2\x11.url.Url.LocationR\fdstLocationsB\b\n" +
	"\x06_stops\"*\n" +
	"\x05Stops\x12\v\n" +
	"\aNONSTOP\x10\x00\x12\t\n" +
	"\x05STOP1\x10\x01\x12\t\n" +
	"\x05STOP2\x10\x02\"8\n" +
	"\fLocationType\x12\x11\n" +
	"\rUNSPECIFIED_L\x10\x00\x12\v\n" +
	"\aAIRPORT\x10\x01\x12\b\n" +
	"\x04CITY\x10\x02\"Z\n" +
	"\bTraveler\x12\x11\n" +
	"\rUNSPECIFIED_T\x10\x00\x12\t\n" +
	"\x05ADULT\x10\x01\x12\t\n" +
	"\x05CHILD\x10\x02\x12\x11\n" +
	"\rINFANT_ON_LAP\x10\x03\x12\x12\n" +
	"\x0eINFANT_IN_SEAT\x10\x04\"Y\n" +
	"\x05Class\x12\x15\n" +
	"\x11UNSPECIFIED_CLASS\x10\x00\x12\v\n" +
	"\aECONOMY\x10\x01\x12\x13\n" +
	"\x0fPREMIUM_ECONOMY\x10\x02\x12\f\n" +
	"\bBUSINESS\x10\x03\x12\t\n" +
	"\x05FIRST\x10\x04\"=\n" +
	"\bTripType\x12\x14\n" +
	"\x10UNSPECIFIED_TRIP\x10\x00\x12\x0e\n" +
	"\n" +
	"ROUND_TRIP\x10\x01\x12\v\n" +
	"\aONE_WAY\x10\x02B6Z4github.com/tobyrushton/gflights/flights/internal/urlb\x06proto3"

var (
	file_url_proto_rawDescOnce sync.Once
	file_url_proto_rawDescData []byte
)

func file_url_proto_rawDescGZIP() []byte {
	file_url_proto_rawDescOnce.Do(func() {
		file_url_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_url_proto_rawDesc), len(file_url_proto_rawDesc)))
	})
	return file_url_proto_rawDescData
}

var file_url_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_url_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_url_proto_goTypes = []any{
	(Url_Stops)(0),        // 0: url.Url.Stops
	(Url_LocationType)(0), // 1: url.Url.LocationType
	(Url_Traveler)(0),     // 2: url.Url.Traveler
	(Url_Class)(0),        // 3: url.Url.Class
	(Url_TripType)(0),     // 4: url.Url.TripType
	(*Url)(nil),           // 5: url.Url
	(*Url_Location)(nil),  // 6: url.Url.Location
	(*Url_Flight)(nil),    // 7: url.Url.Flight
}
var file_url_proto_depIdxs = []int32{
	7, // 0: url.Url.flight:type_name -> url.Url.Flight
	2, // 1: url.Url.travelers:type_name -> url.Url.Traveler
	3, // 2: url.Url.class:type_name -> url.Url.Class
	4, // 3: url.Url.tripType:type_name -> url.Url.TripType
	1, // 4: url.Url.Location.type:type_name -> url.Url.LocationType
	0, // 5: url.Url.Flight.stops:type_name -> url.Url.Stops
	6, // 6: url.Url.Flight.srcLocations:type_name -> url.Url.Location
	6, // 7: url.Url.Flight.dstLocations:type_name -> url.Url.Location
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_url_proto_init() }
func file_url_proto_init() {
	if File_url_proto != nil {
		return
	}
	file_url_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_url_proto_rawDesc), len(file_url_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_url_proto_goTypes,
		DependencyIndexes: file_url_proto_depIdxs,
		EnumInfos:         file_url_proto_enumTypes,
		MessageInfos:      file_url_proto_msgTypes,
	}.Build()
	File_url_proto = out.File
	file_url_proto_goTypes = nil
	file_url_proto_depIdxs = nil
}
